### ISSUE TITLE
add a tile to volumio UI to provide the latest additions to the  local library

### ISSUE THREAD

**Issue by pattdepanick** [pattdepanick/vlub#17]

**Comment by bcornec** [comment]
Is it for volumio upstream or vlub ?

**Comment by pattdepanick** [comment]
has to be developped as a plugin for volumio

**Comment by pattdepanick** [comment]
Work in progress. Have to leverage the existing musical library tile and adapt it to show only the last 50 additions in the library

**Comment by pattdepanick** [comment]
Followup in #24
