### ISSUE TITLE
Volumio 3 install Issues

### ISSUE THREAD

**Issue by pattdepanick** [pattdepanick/vlub#33]
In Install.sh:
Issue1 : the pip install lcd2usb line will install the latest versions of lcd2usb and libusb1 (version 2.xxxx).
The version 2.x of libusb crashes during the pip install because of htmlparser 
One needs to install an earlier version (version 1.92) to get things working
pip install libusb1==1.9.2

Issue 2 : somehow it seems that requests module was missing from our installer too.
pip install request

vlub is working properly with these 2 fixes on volumio 3

**Comment by bcornec** [comment]
> pip install requests
